/* Generated by Together */

package impl.miw.business.viajemanager;

import java.util.Map;
import java.util.Vector;

import org.springframework.beans.factory.annotation.Autowired;

import com.miw.business.ViajeManagerService;
import com.miw.model.Iva;
import com.miw.model.ParamBusquedaViaje;
import com.miw.model.Viaje;
import com.miw.persistence.IvaDataService;
import com.miw.persistence.ViajeDataService;

public class ViajeManager implements ViajeManagerService {

	@Autowired
	private ViajeDataService viajeDataService;
	
	@Autowired
	private IvaDataService ivaDataService;
	
	//private Map<Integer,Integer> disccounts;
	
	
/*
	public void setDisccounts(Map<Integer,Integer> disccounts) {
		System.out.println("Recibidos los descuentos por familia: "+disccounts);
		this.disccounts = disccounts;
	}
*/
	public void setViajeDataService(ViajeDataService viajeDataService) {
		this.viajeDataService = viajeDataService;
	}

	public void setIvaDataService(IvaDataService ivaDataService) {
		this.ivaDataService = ivaDataService;
	}

	public Vector<Viaje> getViajes() throws Exception
	{
		
		Vector<Viaje> viajes = viajeDataService.getViajes();
		//Vector<Iva> ivas= ivaDataService.getIvas();
		/*
		for ( Viaje viaje: viajes)
		{
			for ( Iva iva:ivas)
			{
				if ( book.getFamily()==iva.getFamily())
				{
					//Aplicamos el descuento por familia al calcular el precio
					book.setPrice(book.getBasePrice()*iva.getValue()*(100-disccounts.get(book.getFamily() ) )/100 );
					
				}
			}
		}
		*/
		return viajes;
	}
	
	@Override
	public int getPlazasLibresViaje(Viaje viaje) throws Exception {
		int plazasLibres = viajeDataService.getPlazasLibresViaje(viaje);
		return plazasLibres;
	}

	@Override
	public Vector<Viaje> getViajesIda(ParamBusquedaViaje paramBusquedaViaje) throws Exception {
		Vector<Viaje> viajes = viajeDataService.getViajesIda(paramBusquedaViaje);
		return viajes;
	}
	
	@Override
	public Vector<Viaje> getViajesVuelta(ParamBusquedaViaje paramBusquedaViaje) throws Exception {
		Vector<Viaje> viajes = viajeDataService.getViajesVuelta(paramBusquedaViaje);
		return viajes;
	}
	
	public boolean hayViajesConPlazasLibres(ParamBusquedaViaje paramBusquedaViaje) throws Exception{
		return viajeDataService.hayViajesConPlazasLibres(paramBusquedaViaje);
	}

	@Override
	public Viaje getViaje(Viaje viaje) throws Exception {
		return viajeDataService.getViaje(viaje);
	}
	
	
	
	
	
	/*
	@Override
	public Book getSpecialOffer() throws Exception
	{
		Vector<Book> books = getBooks();
		int number = (int) (Math.random()*books.size()-1);
		System.out.println("Aplicando descuento a "+books.elementAt(number).getTitle());
		books.elementAt(number).setPrice((double)books.elementAt(number).getPrice()*0.9);
		return books.elementAt(number);
	}

	public Book newBook(Book book) throws Exception {
		// TODO Auto-generated method stub
		return this.bookDataService.newBook(book);
	}
	*/
	
}
