/* Generated by Together */

package impl.miw.business.bookmanager;

import java.util.Map;
import java.util.Vector;

import org.springframework.beans.factory.annotation.Autowired;

import com.miw.business.BookManagerService;
import com.miw.model.Book;
import com.miw.model.Iva;
import com.miw.persistence.BookDataService;
import com.miw.persistence.IvaDataService;

public class BookManager implements BookManagerService {

	@Autowired
	private BookDataService bookDataService;
	@Autowired
	private IvaDataService ivaDataService;
	
	private Map<Integer,Integer> disccounts;
	
	

	public void setDisccounts(Map<Integer,Integer> disccounts) {
		System.out.println("Recibidos los descuentos por familia: "+disccounts);
		this.disccounts = disccounts;
	}

	public void setBookDataService(BookDataService bookDataService) {
		this.bookDataService = bookDataService;
	}

	public void setIvaDataService(IvaDataService ivaDataService) {
		this.ivaDataService = ivaDataService;
	}

	public Vector<Book> getBooks() throws Exception
	{
		
		Vector<Book> books = bookDataService.getBooks();
		Vector<Iva> ivas= ivaDataService.getIvas();
		for ( Book book:books)
		{
			for ( Iva iva:ivas)
			{
				if ( book.getFamily()==iva.getFamily())
				{
					//Aplicamos el descuento por familia al calcular el precio
					book.setPrice(book.getBasePrice()*iva.getValue()*(100-disccounts.get(book.getFamily() ) )/100 );
					
				}
			}
		}
		return books;
	}
	
	@Override
	public Book getSpecialOffer() throws Exception
	{
		Vector<Book> books = getBooks();
		int number = (int) (Math.random()*books.size()-1);
		System.out.println("Aplicando descuento a "+books.elementAt(number).getTitle());
		books.elementAt(number).setPrice((double)books.elementAt(number).getPrice()*0.9);
		return books.elementAt(number);
	}

	public Book newBook(Book book) throws Exception {
		// TODO Auto-generated method stub
		return this.bookDataService.newBook(book);
	}
}
